### ISSUE TITLE
ends vs interior

### ISSUE THREAD

**Issue by devonorourke** [rrwick/Polypolish#1]
Hi Ryan,

Thank you not only for the addition of a promising new tool, but the clarity in your writing and helpful examples contained within this repo. After reviewing your [Toy example](https://github.com/rrwick/Polypolish/wiki/Toy-example) data to better understand the motivation behind this tool, it dawned on me that all of the errors being corrected happened to be internal to the reference sequence. That is, corrections weren't ever happening on the flanks of the `draft.fasta` reference.

It got me to wondering whether a polishing tool could handle a (literal?) edge case: a scenario where a set of reads would indicate additional sequence data should be added to the beginning or end of a read... (if only you could get the aligner to see them...). I suspected the answer is that a polisher can only work with what an aligner can align, so I started by trying to understand how many bases of a reference end I could lose before those reads that should be aligning to the edge would be retained by the aligner.

I took the original draft.fasta file and removed either 6bp or 1bp from the right side (end) of the sequence:
```
## original reference sequence: start---> GACTGTTCAACGCGA...{70 more bases}...CGTGTGGAGCTGCG <--end
## 1bp-chop'd reference seq:    start---> GACTGTTCAACGCGA...{70 more bases}...CGTGTGGAGCTGC 
## 6bp-chop'd reference seq:    start---> GACTGTTCAACGCGA...{70 more bases}...CGTGTGGA  

```

I started by taking your [draft.fasta](https://github.com/rrwick/Polypolish/wiki/files/toy_example/assembly.fasta) file and chopping off either 1bp or 6bp of sequence data, then ran the same parameters executed to generate the [alignments.sam](https://raw.githubusercontent.com/wiki/rrwick/Polypolish/files/toy_example/alignments.sam) file:
```
cut -c 1-94 originalDraft.fasta | sed 's/draft/less6bp/' > less6bpRightEnd.fasta
bwa index less6bpRightEnd.fasta
bwa mem -a -k1 -T7 -A1 -B1 -O1 -E1 -L100 less6bpRightEnd.fasta reads.fastq > less6bpRightEnd_alignments.sam

cut -c 1-99 originalDraft.fasta | sed 's/draft/less1bp/' > less1bpRightEnd.fasta
bwa index less1bpRightEnd.fasta
bwa mem -a -k1 -T7 -A1 -B1 -O1 -E1 -L100 less1bpRightEnd.fasta reads.fastq > less1bpRightEnd_alignments.sam
```

When you chop off the last 6 bases of the reference, you end up failing to align 4 reads, all with sequence `TGGAGCTGCG`, which is the last 10 bp of the original reference sequence: 
```
samtools view -f 4 less6bpRightEnd_alignments.sam
```
produces:
```
read_20	4	*	0	0	*	*	0	0	TGGAGCTGCG	KKKKKKKKKK	AS:i:0	XS:i:0
read_47	4	*	0	0	*	*	0	0	TGGAGCTGCG	KKKKKKKKKK	AS:i:0	XS:i:0
read_56	4	*	0	0	*	*	0	0	TGGAGCTGCG	KKKKKKKKKK	AS:i:0	XS:i:0
read_74	4	*	0	0	*	*	0	0	TGGAGCTGCG	KKKKKKKKKK	AS:i:0	XS:i:0
```

However, you _do_ manage to map those same reads when you chop off only 1 bp from the original reference:
```
read_20	0	less1bp	91	20	9M1I	*	0	0	TGGAGCTGCG	KKKKKKKKKK	NM:i:1	MD:Z:9	AS:i:9	XS:i:5
read_47	0	less1bp	91	20	9M1I	*	0	0	TGGAGCTGCG	KKKKKKKKKK	NM:i:1	MD:Z:9	AS:i:9	XS:i:
read_56	0	less1bp	91	20	9M1I	*	0	0	TGGAGCTGCG	KKKKKKKKKK	NM:i:1	MD:Z:9	AS:i:9	XS:i:5
read_74	0	less1bp	91	20	9M1I	*	0	0	TGGAGCTGCG	KKKKKKKKKK	NM:i:1	MD:Z:9	AS:i:9	XS:i:5
```

So what happens if you run Polypolish with either of these `.sam` files where we map the reads to either a 1-bp or 6-bp truncated reference? For simplicity, I set the `--min_depth` argument to **1**:
```
./polypolish less6bpRightEnd.fasta less6bpRightEnd_alignments.sam --min_depth 1 > less6bpRightEnd_polished.fasta
./polypolish less1bpRightEnd.fasta less1bpRightEnd_alignments.sam --min_depth 1 > less6bpRightEnd_polished.fasta
```

As expected, the `less6bpRightEnd_polished.fasta` didn't include those last 6 bases of the original reference, because the alignment file had no information to support that data as ever existing. 

What surprised me a bit though was that the `less1bpRightEnd_polished.fasta` remained only 99 bases long. The 1bp insertion hinted at by the CIGAR string in the `less1bpRightEnd_alignments.sam` file didn't seem to be used, producting this polished sequence:
```
>less1bp_polypolish
GACTGTTCAACGCGATCGCTGTATTCACCAAGGTTCTTCGGCCTTCACGTACTCTGCGCTATCTGTATTCACCAAGGTTCTTAACTCGTGTGGAGCTGC
```

---

I'd love to get your two cents about what you would expect to happen in this latter scenario where the aligner did  manage to map these little reads, and suggested that there was an insertion in the end of the assembly. However, because the assembly is only beginning as an expected 99-bp file, does Polypolish end once it's satisfied that it's moved along the first 99 positions?

Sorry to raise a likely edge case for edge cases. Thanks again for your insights and tools.

Cheers

**Comment by rrwick** [comment]
The answer relates to your other question about end-to-end alignments (#2). Polypolish is discarding those alignments because they don't start/end in a match. Even if you changed Polypolish to keep those alignments, the [alignment trimming](https://github.com/rrwick/Polypolish/wiki/Alignment-trimming) logic would prevent these end-of-sequence errors from being fixed.

I think I'd like to keep Polypolish _not_ trying to add bases at the start/end of sequences, because with circular sequences (which are the typical case for bacterial genomes), this gets tricky.

I made a new item to Polypolish's FAQ which discusses this:
[Can Polypolish add/remove bases at the start/end of a sequence?](https://github.com/rrwick/Polypolish/wiki/FAQ-and-miscellaneous-tips#can-polypolish-addremove-bases-at-the-startend-of-a-sequence)

Thanks!
