### ISSUE TITLE
Changes file

### ISSUE THREAD

**Issue by suzukimicro** [rrwick/Polypolish#13]
Hi, 
Is it possible for Polypolish to extract information on corrected bases like changes file in Pilon?
Best,
Masato

**Comment by rrwick** [comment]
Hi Masato,

If you run Polypolish with `--debug` you can generate a per-base TSV file. See [this wiki page](https://github.com/rrwick/Polypolish/wiki/Toy-example#debug-output) for an example. Grepping for `changed` in that file should reveal any bases which were changed.

However, I usually find it easier to do a before-vs-after global alignment. See [this wiki page](https://github.com/rrwick/Polypolish/wiki/Manual-inspection-of-results) for a script that makes human-readable outputs of changed regions.

Ryan
