### ISSUE TITLE
Error: query name contig_1214 in SAM but not in assembly

### ISSUE THREAD

**Issue by FA387** [rrwick/Polypolish#18]
I do not know exactly the problem with 
So I have assembled the MAGs from Nanopore sequence. I want to polish this MAGs with paired ends Illumina data. I followed the instruction on the Wiki. But there is an error.

I index and generate the sam files of the Illumina reads to the the contigs file, generated from metaflye. I used this contig file to binned MAGs using metabat. 

When I ran the polypolish, to polish the MAGs I use the sam files generated from the contigs flye. Is this the cause of the problem? Should I individually indexed and generated each MAGs to the  Illumina reads?

Sorry I am a novice in Bioinformatics and English is not my first language

**Comment by rrwick** [comment]
Yes, I think that's the problem. You'll need to align to the same contigs that you give to Polypolish. So if you want to polish the MetaBAT contigs, you should make sam files using the MetaBAT contigs.

Hope that helps!

Ryan
