### ISSUE TITLE
Suggesting the use of `anyhow` or `thiserror`

### ISSUE THREAD

**Issue by lavafroth** [rrwick/Polypolish#19]
Hello, I've been going through some of the code in `alignments.rs` and a common pattern I have observed in quite a few functions is that in case of an error, they bail with some formatted text explaining the error. I'd suggest using the [bail! macro from the `anyhow` crate](https://docs.rs/anyhow/latest/anyhow/macro.bail.html) to do this instead of a manual implementation like `quit_with_error`. If you wish to have more structured errors than simple formatted strings, there is the `thiserror` crate which eases the creation of new error structures.

Edit: I'm willing to help write code for this!

**Comment by rrwick** [comment]
Thanks, but this requirement puts me off:
> The surrounding function’s or closure’s return value is required to be `Result<_,[anyhow::Error]`.

This means `bail!` would not be a drop-in replacement for my `quit_with_error`. And since my implementation is just a few lines of code, I'm happy to leave it as is.
