### ISSUE TITLE
loading alignment step: end-to-end filter question

### ISSUE THREAD

**Issue by devonorourke** [rrwick/Polypolish#2]
Hi Ryan,

I started testing out Polypolish on some of my own data today; here's a bit of output that Polypolish reported:
```
Loading alignments (2021-09-16 11:18:32)
test_aligns_1.sam: 820 alignments from 820 reads
test_aligns_2.sam: 842 alignments from 842 reads

Filtering for high-quality end-to-end alignments:
  405 alignments kept
  1,257 alignments discarded
```

I hadn't realized that there was a requirement for end-to-end alignments initially when reviewing the (very well documented!) wiki or help menus. Can you help me understand where in the code this filtering step is being applied? Is there a way to deactivate it, and allow _any_ of the data in the `.sam` files to be incorporated into the pileup counting? 

Thanks!

**Comment by rrwick** [comment]
Unfortunately, it wouldn't be a trivial thing to change. While you could remove the call to `starts_and_ends_with_match` (on [line 209 of `alignment.rs`](https://github.com/rrwick/Polypolish/blob/main/src/alignment.rs#L209)), this will lead to a crash later on when Polypolish processes the CIGAR strings of alignments.

If it helps to shed some light on things, I've added this to Polypolish's FAQ page:
[Why does Polypolish only use end-to-end alignments?](https://github.com/rrwick/Polypolish/wiki/FAQ-and-miscellaneous-tips#why-does-polypolish-only-use-end-to-end-alignments)

If you _really_ wanted to keep clipped alignments, it could probably be done with some extra code in the CIGAR processing. But I'm doubtful that it would improve Polypolish's performance and might often make things worse. Is there a particular reason you want to keep them?

Ryan

**Comment by rrwick** [comment]
Now that I've read issue #1, I think I see what you were getting at. I should have read the issues in chronological order :smile:

Since I'm declaring start/end errors as out-of-scope for Polypolish, I'll close this issue now. But let me know if I've missed something or if you have any more questions!
