### ISSUE TITLE
Suggestion for local realignment 

### ISSUE THREAD

**Issue by YannDussert** [rrwick/Polypolish#22]
Hi,

First thanks for developing Polypolish!

About your search for a way to do local realignment before polishing: freebayes includes a local realignment module, bamleftalign (https://github.com/freebayes/freebayes/blob/master/src/bamleftalign.cpp). Not sure at all it suits your needs, but I thought I should mention it.

Best regards,
Yann

**Comment by rrwick** [comment]
Thank you for that, but if I'm understanding correctly, this tool does _left_ alignment not [local realignment](https://github.com/rrwick/Polypolish/wiki/Local-realignment).

For example, it would take this alignment:
```
read: ACGAT--CG
ref:  ACGATATCG
```
And turn it into this:
```
read: ACG--ATCG
ref:  ACGATATCG
```

This helps multiple alignments over the same region to agree with each other, but it acts on each alignment individually, so it's not quite the same thing as local realignment.

Even though I still haven't found an easy way to do local realignment before Polypolish, I suspect it wouldn't make too much difference. It would likely only affect alignments that end near an indel, so in most cases there should be plenty of reads which have the indel in their middle, allowing Polypolish to fix the error.

Ryan
