### ISSUE TITLE
Lowering memory usage

### ISSUE THREAD

**Issue by zephyris** [rrwick/Polypolish#25]
Fantastic tool, but it is very memory hungry. I've been trying to use it to polish some medium-size (~30-50Mb) repetitive eukaryotic genomes and rapidly reach my available memory.

I think there are two places that could be optimised for reduced memory usage:
First, the process of re-pairing reads loads the entire alignment file. I don't think that is necessary - with normal assumptions about the data order in bwa/sam files, this can be handled streaming the data (either from bwa output, or reading a file) instead of loading the entire alignment into memory.
Second, I think the polishing of each contig/chromosome could be handled independently - essentially chopping the workload into smaller subloads.

I've been playing with these ideas, initially chopping the input fasta and filtered sam file into separate contigs before polypolish (which seems to work identically), and then extending that to write a Python wrapper for bwa which can output the re-paired reads optionally split per contig. I've put the module up here:  [polyalign](https://github.com/zephyris/polyalign/). This doesn't have amazing performance, Python is certainly not the best way to handle this quantity of data, but does alleviate the memory problem.

There is a very real chance I've got a naive misunderstanding, but I hope this might be a useful insight and useful example code.

**Comment by rrwick** [comment]
Polypolish can indeed be memory hungry, especially for larger and/or repetitive genomes. I developed it for bacterial genomes, so while you're welcome to try it on eukaryote genomes, you do so at your own risk :smile:

Thanks for developing and sharing polyalign - I've linked to it from the [Polypolish FAQ entry about eukaryote genomes](https://github.com/rrwick/Polypolish/wiki/FAQ-and-miscellaneous-tips#does-polypolish-work-on-eukaryote-genomes).

Ryan

**Comment by zephyris** [comment]
Thanks! I appreciate the link.
