### ISSUE TITLE
Log output option needed 

### ISSUE THREAD

**Issue by lborcard** [rrwick/Polypolish#26]
Dear rrwick,

Thanks for this great contribution. I recently used your tools and I saw the output in the stderr but I did not find the option to output the logs of each polypolish run. I think it would be great to have them. 

best,

Loïc

**Comment by rrwick** [comment]
While this isn't possible in Polypolish itself, you can redirect its output to a file which will serve as a log. I've created [this new entry](https://github.com/rrwick/Polypolish/wiki/FAQ-and-miscellaneous-tips#saving-polypolishs-log-to-file) in Polypolish's FAQ which shows how to do this.

Thanks for the suggestion!

**Comment by lborcard** [comment]
Thanks for the quick answer, I ended up doing exactly that. Thanks for the great tools! have a good day.
ps: out of curiosity how come is it not possible to do in polypolish ? is it a missing feature in rust ?

**Comment by rrwick** [comment]
It would be possible in Rust, but I didn't include it for simplicity. And also laziness, perhaps :smile:

While I'm still supporting Polypolish (e.g. minor updates and bug fixes), I have no plans to add any major new features, so it will probably stay log-free. But I've labelled this issue as an enhancement request in case I someday do major development on it.
