### ISSUE TITLE
Are bases with "a depth of zero" corrected?

### ISSUE THREAD

**Issue by ilnamkang** [rrwick/Polypolish#5]
Hi,

Thank you for a great tool!!

I have a question on behavior(?) of Polypolish.

Below is one of my Polypolish log file.

\-------
Polishing contig_1 (2,716,937 bp):
  mean read depth: 737.2x
  148 bp have a depth of zero (99.9946% coverage)
  10,032 positions changed (0.3692% of total positions)
  estimated pre-polishing sequence accuracy: 99.6308%
\------

In this case, does Polypolish correct (delete?) the 148 bp with a depth of zero?

Thanks.

**Comment by rrwick** [comment]
Any bases with a depth below the `--min_depth` value (default is 5) are left unchanged, and this applies to bases with a depth of zero. So no, they will not be deleted.

This follows Polypolish's general philosophy: when in doubt, don't change anything. Polypolish assumes that your input assembly is mostly correct and just needs some small-scale fixes (like homopolymer lengths). So Polypolish will not make any significant changes to your assembly - other polishers like Pilon are better at that. But it also means that Polypolish is very unlikely to _introduce_ any errors.

Ryan
