### ISSUE TITLE
Docker image for polypolish

### ISSUE THREAD

**Issue by maxbranger** [rrwick/Polypolish#8]
Hello,
just a quick word for information.
for my own usage, I've made a docker image that i released on dockerhub publically.
https://hub.docker.com/r/maximebranger/polypolish
It integrates last version of polypolish (0.5.0).
Thank you for your job guys.

**Comment by rrwick** [comment]
Thanks! I've added a bit to the [installation page on the wiki](https://github.com/rrwick/Polypolish/wiki/Installation) which links to this.

Ryan
