### ISSUE TITLE
Bad sam files (Cigar and read don't match) when using BWA but works with bowtie2 

### ISSUE THREAD

**Issue by UriNeri** [rrwick/Polypolish#9]
Hi Ryan!  
first of, thanks for making such great tools :-)  
I'm trying to polish a (newly made) PacBio flye assembly using some (weird old) PE Illumina reads.  
I seem to have some issue with the sam files which [ValidateSamFile](http://broadinstitute.github.io/picard/command-line-overview.html#ValidateSamFile) seem to verify.  
Oddly enough, I'm getting them only when I use bwa, where `polypolish`  finished successfully when I try bowtie2 (btw, in the wiki [Can I use Bowtie2 instead of BWA-MEM?](https://github.com/rrwick/Polypolish/wiki/FAQ-and-miscellaneous-tips#can-i-use-bowtie2-instead-of-bwa-mem) I think you forgot to first index the draft.fasta, i.e. 
```
bowtie2-build draft.fasta index
bowtie2 -a -p 16 -x index -U reads_1.fastq.gz > alignments_1.sam
bowtie2 -a -p 16 -x index -U reads_2.fastq.gz > alignments_2.sam
``` 
At least, I couldn't use the fasta directly).  
The polypolish output when using the bowtie2 sams as input is longer so I'm attaching it as .txt, 
[pp_sout_bowtie2.txt](https://github.com/rrwick/Polypolish/files/8442715/pp_sout_bowtie2.txt)
but here is the bwa input:
```
 polypolish $PacBio_flye_assembly filtered_1.sam filtered_2.sam > polished.fasta


Starting Polypolish (2022-04-07 14:30:44)
    Polypolish is a tool for polishing genome assemblies with short reads. Unlike other tools in this category, Polypolish uses SAM files where
each read has been aligned to all possible locations (not just a single best location). This allows it to repair errors in repeat regions that
other alignment-based polishers cannot fix.

Polypolish version: 0.5.0

Input assembly:
  /media/HDD1/uri/projects/Atlit_Isolates/47N/Reassembly/input/PacBio_flye_assembly.fasta

Input short-read alignments:
  filtered_1.sam
  filtered_2.sam

Settings:
  --fraction_invalid 0.2
  --fraction_valid 0.5
  --max_errors 10
  --min_depth 5
  not logging debugging information


Loading assembly (2022-04-07 14:30:44)
contig_1 (43,189 bp)
contig_10 (443,126 bp)
contig_11 (226,743 bp)
contig_2 (100,290 bp)
contig_3 (4,918 bp)
contig_4 (57,405 bp)
contig_5 (2,492,393 bp)
contig_6 (94,373 bp)
contig_7 (297,562 bp)
contig_8 (9,975 bp)
contig_9 (7,069 bp)


Loading alignments (2022-04-07 14:30:44)

Error: CIGAR string for read HWI-M01759:27:000000000-ANA6V:1:1117:14253:14897 does not match read sequence
```    
I'm really not sure why or how this error came to be (I pre-proccessed the reads crudely and might have messed something up), but thought I'd share this in case you can make sense of it (or if other folks find it useful).   (So sorry for the many edits, I of course I forgot to attach the .txt file...)

**Comment by rrwick** [comment]
That is indeed a very strange error. I've never seen it occur before - that code was just in Polypolish as a sanity check, i.e. it's not supposed to fail!

This error is basically saying that in an alignment of that read, the CIGAR string doesn't match the read's length. As a simple example, imagine an alignment line with a read sequence of `ATTTATCGCG` and a CIGAR of 11M. This would result in the error because the sequence is 10 bp long but the CIGAR implies a sequence of 11 bp.

If you still have the alignments, it'd be interesting to see what the alignment for this read looks like:
```bash
grep 'HWI-M01759:27:000000000-ANA6V:1:1117:14253:14897' filtered_1.sam
```

**Comment by rrwick** [comment]
Also, thanks for pointing out the lack of indexing in the FAQ - I've fixed that now!

**Comment by rrwick** [comment]
Closing this issue now due to age.
